function [string] = LoadSeriesInstance(SeriesInstance)
global sel

S.fh = figure('units','pixels',...
              'position',[300 300 550 200],...
              'menubar','none',...
              'name','SeriesIstanceUID',...
              'numbertitle','off',...
              'resize','off');
          
S.bg = uibuttongroup('units','pix',...
                     'pos',[20 100 515 90]);
   
for i = 1 : size(SeriesInstance,2)
    S.rd(i) = uicontrol(S.bg,...
                    'style','rad',...
                    'unit','pix',...
                    'position',[20 55-22*(i-1) 460 30],...
                    'string',SeriesInstance(1,i).UID);
                
end

S.pb = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[180 20 200 30],...
                 'string','Select',...
                 'callback',{@pb_call, S});
waitfor(S.fh)
string = SeriesInstance(1,round(sel)-round(S.rd(1))+1).UID;

   
function [] = pb_call(varargin)
% Callback for pushbutton.
% Get the structure.
global sel
S = varargin{3};
sel = findobj(get(S.bg,'selectedobject'));
delete(S.fh)